// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentPayments_API.Data;
using StudentPayments_API.Models.Enums;

#nullable disable

namespace StudentPayments_API.Migrations
{
    [DbContext(typeof(StudentPaymentsDbContext))]
    [Migration("20260305112921_AddStudentDuesType")]
    partial class AddStudentDuesType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "currency_enum", "currency_enum", new[] { "kes", "usd", "eur", "gbp" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enrollment_enum", "enrollment_status_enum", new[] { "active", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "idempotency_resource_type_enum", "idempotency_resource_type_enum", new[] { "payment_transaction" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_channel_enum", "payment_channel_enum", new[] { "mobile_banking", "internet_banking" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_transaction_status_enum", "payment_transaction_status_enum", new[] { "success", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_type_enum", "payment_type_enum", new[] { "cash", "check", "pesalink" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "program_enum", "program_enum", new[] { "computer_science", "law", "international_relations" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BankClientId")
                        .HasColumnType("integer");

                    b.Property<string>("BankReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<CurrencyEnum>("CurrencyType")
                        .HasColumnType("currency_enum");

                    b.Property<int>("IdempotencyKeyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("InternalReference")
                        .HasColumnType("uuid");

                    b.Property<PaymentChannelEnum>("PaymentChannel")
                        .HasColumnType("payment_channel_enum");

                    b.Property<PaymentTypeEnum>("PaymentType")
                        .HasColumnType("payment_type_enum");

                    b.Property<PaymentTransactionStatusEnum>("Status")
                        .HasColumnType("payment_transaction_status_enum");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("IdempotencyKeyId");

                    b.HasIndex("InternalReference")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("BankClientId", "BankReference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransaction_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("StudentPayments_API.Models.BankClient", b =>
                {
                    b.Property<int>("BankClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankClientId"));

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("BankClientId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("BankClients");
                });

            modelBuilder.Entity("StudentPayments_API.Models.IdempotencyKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<IdempotencyResourceTypeEnum>("ResourceType")
                        .HasColumnType("idempotency_resource_type_enum");

                    b.HasKey("Id");

                    b.HasIndex("BankClientId", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("StudentPayments_API.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<EnrollmentStatusEnum>("EnrollmentStatus")
                        .HasColumnType("enrollment_status_enum");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<ProgramEnum>("Program")
                        .HasColumnType("program_enum");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Student");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId");

                    b.HasIndex("AdmissionNumber")
                        .IsUnique();

                    b.ToTable("students");
                });

            modelBuilder.Entity("StudentPayments_API.Models.StudentDues", b =>
                {
                    b.Property<int>("DueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DueId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DuesAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("DuesType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DueId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDues", t =>
                        {
                            t.HasCheckConstraint("CK_StudentDues_DueType", "\"DuesType\" IN ('Tuition', 'Hostel', 'Library', 'Lab', 'Sports', 'Other')");

                            t.HasCheckConstraint("CK_StudentDues_DuesAmount", "\"DuesAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("PaymentTransaction", b =>
                {
                    b.HasOne("StudentPayments_API.Models.BankClient", "BankClient")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("BankClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPayments_API.Models.IdempotencyKey", "IdempotencyKey")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("IdempotencyKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentPayments_API.Models.Student", "Student")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankClient");

                    b.Navigation("IdempotencyKey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPayments_API.Models.IdempotencyKey", b =>
                {
                    b.HasOne("StudentPayments_API.Models.BankClient", "BankClient")
                        .WithMany("IdempotencyKeys")
                        .HasForeignKey("BankClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankClient");
                });

            modelBuilder.Entity("StudentPayments_API.Models.StudentDues", b =>
                {
                    b.HasOne("StudentPayments_API.Models.Student", "Student")
                        .WithMany("StudentDues")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentPayments_API.Models.BankClient", b =>
                {
                    b.Navigation("IdempotencyKeys");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("StudentPayments_API.Models.IdempotencyKey", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("StudentPayments_API.Models.Student", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("StudentDues");
                });
#pragma warning restore 612, 618
        }
    }
}
