apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: studentpayments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: studentpayments
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi